server:
  servlet:
    context-path: /api-business
  port: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
      
path:
  repo:
    idea: /repository/documentos/usuario/
    comentarios: /repository/documentos/comentario/

logging:
  level:
    co:
      com:
        ud:
          business:
            rest:
              client: DEBUG


jwt:
  secret: a6e21884876f43819523c31033fa697e

repositorio:
  formatoArt:
    ubicacion: C:\\repository\\documentos\\formatos\\formato_002.docx
    docDestino: /repository/documentos/articulos/
  formato:
    ubicacion: C:\\repository\\documentos\\formatos\\formato_001.docx

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.0.30:9411
    #sender:
    #  type: rabbit
      
endpoint:
  ms-acceso-datos:
    protocol: http://
    host: localhost
    port: 5003
    base: /api-datos
    controlLectura:
      version: /v.1
      url: /controllectura
      name: controlLecturaCliente
    comentariosArt:
      version: /v.1
      url: /comentarioarticulo
      name: comentarioArtCliente
    comentarios:
      version: /v.1
      url: /comentario
      name: comentarioCliente
    articulos:
      version: /v.1
      url: /articulos
      name: articulosCliente
    formato-ideas:
      version: /v.1
      url: /formatoidea
      name: formatoIdeasCliente
    ideas:
      version: /v.1
      url: /ideas
      name: ideasCliente
    personas:
      version: /v.1
      url: /personas
      name: personasCliente
    usuarios:
      version: /v.1
      url: /usuarios
      name: usuariosCliente
   
