server:
  servlet:
    context-path: /api-datos
  port: 5003
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://databasearticulos:5432/articuloss
    username: postgres
    password: 12345678
  liquibase:
    change-log: classpath:/db/db.changelog.xml
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    generate-ddl: true
  org:
    hibernate:
      envers:
        audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
        audit_strategy_validity_store_revend_timestamp: true
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.0.30:9411
    #sender:
    #  type: rabbit
#show sql values
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
