server:
  servlet:
    context-path: /api-business
  port: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka


logging:
  level:
    co:
      com:
        ud:
          business:
            rest:
              client: DEBUG

jwt:
  secret: a6e21884876f43819523c31033fa697e

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: rabbit