server:
  servlet:
    context-path: /api-business
  port: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://server-discovery:1111/eureka

path:
  repo:
    idea: /repository/documentos/usuario/

logging:
  level:
    co:
      com:
        ud:
          business:
            rest:
              client: DEBUG

jwt:
  secret: a6e21884876f43819523c31033fa697e
  
repositorio:
  formato:
    ubicacion: /opt/repository/documentos/formatos/
    comentarios: /opt/repository/documentos/comentario/

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://service-zipkin:9411
    #sender:
      #type: rabbit
      
endpoint:
  ms-acceso-datos:
    protocol: http://
    host: service-acceso-datos
    port: 5003
    base: /api-datos
    comentarios:
      version: /v.1
      url: /comentario
      name: comentarioCliente
    articulos:
      version: /v.1
      url: /articulos
      name: articulosCliente
    formato-ideas:
      version: /v.1
      url: /formatoidea
      name: formatoIdeasCliente
    ideas:
      version: /v.1
      url: /ideas
      name: ideasCliente
    personas:
      version: /v.1
      url: /personas
      name: personasCliente
    usuarios:
      version: /v.1
      url: /usuarios
      name: usuariosCliente
