server:
  port: 5002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411.
    sender:
      type: rabbit
  cloud:
    gateway:
      routes:
        - id: api-acceso-datos
          uri: lb://api-acceso-datos 
          predicates:
           - Path=/api-datos/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: api-business
          uri: lb://api-business 
          predicates:
           - Path=/api-business/**
          filters:
            - RemoveRequestHeader=Cookie
           
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'
