server:
  port: 5002

eureka:
  client:
    serviceUrl:
      defaultZone: http://server-discovery:1111/eureka

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://service-zipkin:9411
    sender:
      type: rabbit
  cloud:
    gateway:
      routes:
        - id: ms-datos
          uri: http://service-acceso-datos:5003/
          predicates:
            - Path=/api-datos/**
        - id: ms-business
          uri: http://service-business:5000/
          predicates:
           - Path=/api-business/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'
